### ISSUE TITLE
Enhancement: Offline mode

### ISSUE THREAD

**Issue by AceDenghar** [lamarios/clipious#134]
Would it be possible to add an offline mode ?

Concerned video could be downloaded on background in a local folder.

Should not be only an option to download video, should be an option Wich could permit to manage offline video (specific tab ?)

We can imagine that an option could be set for a specific channel : every new video of the channel will be downloaded.

Thanks !

Mathieu.

**Comment by Patriot2407** [comment]
+1

**Comment by lamarios** [comment]
This will be a video download option in the  next release with a couple of caveats:

- No quality options for now, invidious only offers 340p and 720p for both video and audio, i don't think 340p is acceptable so it will download 720p.
- no audio only because the app doesn't handle audio only playback

I won't do auto download of new videos of a channel.
