### ISSUE TITLE
Add Share/copy link in video player

### ISSUE THREAD

**Issue by kylrth** [lamarios/clipious#205]
I don't see a way to share or copy a link to the video.

**Comment by lamarios** [comment]
Here? 

![Screenshot_20230618-065654~2](https://github.com/lamarios/clipious/assets/1192563/8b26e2f2-5d6b-4f1e-b25d-58fafb02a47d)

**Comment by kylrth** [comment]
Strange, is the Accrescent release behind?

![Screenshot_20230618-083119](https://github.com/lamarios/clipious/assets/5044802/926fdca5-f1dc-42be-97b4-1a04e085829b)

**Comment by kmccmk9** [comment]
Just commenting to help you out. I also was confused by this. You have to go into settings and disable automatically play video. With that disabled, you will get the screenshot posted above. The only annoyance is there isn't a way to get back to it once you've started watching the video. In order to share a video you're currently watching you must close the video playback and then open the video again to get that initial into screen.

**Comment by lamarios** [comment]
Yup that is correct, that is something i need to fix.

**Comment by lamarios** [comment]
will be on version 1.8.6
