### ISSUE TITLE
Large playlists causing crashes

### ISSUE THREAD

**Issue by WardPearce** [lamarios/clipious#247]
Large playlists (150+ videos) tend to cause Clipious to lag or crash due to excessive memory use. This tends to happen on lower end devices like Smart TVs, probably due to all the videos being loaded all at once.

**Comment by lamarios** [comment]
From my test it is a tv only problem, will look into it.

**Comment by WardPearce** [comment]
> From my test it is a tv only problem, will look into it.

Yea most likely, probably as simple as adding a "Load more" button or smartly loading more once a user scrolls X amount of items down. Not sure if this is implemented on the mobile front, but if not I'd imagine low end mobile phones might have a similar issue.

**Comment by lamarios** [comment]
the issue was that on TV it is using a non scrollable grid which loads all the widgets, while on mobile it uses a scrollable list which loads widgets when needed.

I did this to so there can be more screen space on tv to show the videos. I found a not so elegant alternative, I'll see if i can think of something else before i release this end of the week.
