### ISSUE TITLE
Where are the files downloaded? 

### ISSUE THREAD

**Issue by larry77** [lamarios/clipious#262]
Hello, when I downloaded a v8deo from YouTube on an android phone, to which location is it sent? Is there any way to download it as an audio file?

**Comment by lamarios** [comment]
The file are downloaded in the default app data folder, I don't know the exact path might. You can download audio only since the last version (v1.12.0), there's a download option dialog. 

![Screenshot_20230806-091300](https://github.com/lamarios/clipious/assets/1192563/a84ec45c-fe54-4b0e-a7d7-8e19d0e16860)

**Comment by lamarios** [comment]
I will close this one as i'm not planning to let the user decide where the files will be downloaded. For advanced youtube video downloading, please use [Seal](https://github.com/JunkFood02/Seal)

**Comment by jnishwanth** [comment]
@lamarios is there a way to delete the downloaded videos?

**Comment by lamarios** [comment]
You can swipe from right to left on a video in the downloads section of the app
