### ISSUE TITLE
Please add an option to disable thumbnails, manage downloaded videos(delete them etc.) and save link to a video locally as a playlist since sync with invidious doesnt work so make a temporary solution

### ISSUE THREAD

**Issue by 2000prasanth** [lamarios/clipious#434]
Option to disable thumbnails:
I feel disabling thumbnails is a good option to make videos less distracting. Although Dearrow  exists please add this option.

Manage downloaded videos:
Please add an option to manage downloads(delete etc.) very urgent:

Save video link locally as a playlist, since sync with invidious doesn't work and might be unstable. So I urgently need an option to do this

Option to export Video filters 

Some personal comments:
I liked the app very much due to the video filter feature and sticks to it although newpipe, libretube exists because of this. For me, I get addicted to a certain topic after watching one or two videos and continuously stream similar content and couldn't focus on studies. Now Clipious is the perfect antidote that I founded
 You can market yourself as a distraction free and privacy friendly YouTube alternative to gain the share of users from the newpipe/libretube fraternity.

I hope all the recommendations that I have mentioned will be done, and I will promote the app among my peers.
Thanks a lot!

**Comment by lamarios** [comment]
It's not only against you but too bad it falls on you for this one.  I'm getting tired of this kind of issues / emails i receive where things are "urgent" or "badly needed" or tiny issues that make the app "completely unusable" for someone's very specific use case  or even "app A does this, app B does this but yours doesn't etc", i know the last one it's not your issue per se but i'll group it together. 

This is an app to watch youtube video. Please stop requesting for things like it's life or death and seeing this kind of requests does nothing except making me not wanting to implementing it. Literally NOTHING is urgent about this application so please keep the "I urgently need" stuff as if I owe you something to yourself. 

Also telling me that doing this or that will steal people over other apps or that you'll tell your friend about it does nothing for me. I originally built this for myself because I prefer to use apps instead of website; not to impress or convert random people on the other side of the world.

I'm more than happy to share the app, the code, get feedback and help fix stuff. I'll keep doing it as long as it's fun to do so but the urgency / "this is unusable" needs to stop it **really** kills  the fun out of it. 

The app works and it works pretty well at this point. Again, nothing is urgent.

**Comment by 2000prasanth** [comment]
sorry
