### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by mobsenpai** [lamarios/clipious#478]
**Describe the bug**
Whenever I watch a video with multiple language dubs, It chooses a random language. How can I make it to english or original language? 

Ofc I am taking about Mr beast channel lol. Is there something I am missing cuz there were no issues abt this here.

**Comment by loopernow** [comment]
I'm not the developer but…did you see there is a setting in the Video Player section, "Remember subtitles language"?

**Comment by mobsenpai** [comment]
> I'm not the developer but…did you see there is a setting in the Video Player section, "Remember subtitles language"?

I am talking abt the video language. Youtube allows to select which audio to play. Mr beast's channel has dubbed audio in a single video. So when i play something it does not play in english.

**Comment by loopernow** [comment]
Oh, I see! I wonder if it is choosing an audio track based on your location or perhaps based on your instance location. Because when I play the latest Mr Beast video in Clipious, it plays English. 

I was having an issue earlier (that led me to your Github issue) where subtitles were not showing up even if I selected a subtitle. But then I tried selecting the subtitle on the same instance on a PC web browser, and the same issue occurred, so I realized it was an instance issue. I was able to resolve that issue by switching to an instance that showed subtitles on desktop.

I noticed that mobile YouTube (in an Android web browser) does not let you select the audio track, but the desktop site does…

**Comment by mobsenpai** [comment]
Idk what is doing this.  I have tried changing the instance itself but with the same results.  And even if it works by changing location (haven't tried) i can't be bothered to use a vpn just to watch a youtube video. Also it's not something major,  I don't really watch mrbeast so. It was just something that icked me so just added an issue here.

**Comment by lamarios** [comment]
I believe the issue is from invidious itself. If you try to change the audio track of the player if it's in a wrong language there will be no option for the language itself. Clipious takes the stream data directly from invidious' API. See here also: https://github.com/iv-org/invidious/issues/2007

I believe switching to non-dash stream should fix the issue.

**Comment by mobsenpai** [comment]
Oh yeah, so that's what the problem was. Got it tq mate.
