### ISSUE TITLE
no playable videos on my own instance 

### ISSUE THREAD

**Issue by kubo6472** [lamarios/clipious#5]
Since I don't see this issue on publics, only on mine, however it does work online, without this app, I don't see where the issue could lie.
![Screenshot_20230301-232410_Clipious](https://user-images.githubusercontent.com/26146502/222279417-f0fbaa5f-ac0c-4084-8336-8c3ef930b39f.png)

**Comment by lamarios** [comment]
if you go to 
```
https://<your invidious instance>/api/v1/videos/SurUidVDQf4
```

do the thumbnails urls are displayed with the full path like here:
https://invidious.snopyta.org/api/v1/videos/SurUidVDQf4

if not you need to add the 
```
 domain: yourhost.com
```

to your invidious config. See docs here: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L89

**Comment by kubo6472** [comment]
Two settings that needed to be adjusted were the domain AND the external port. It now works, thanks. A cool app.

**Comment by wisehodl** [comment]
I had this problem as well and solved it with setting the domain and port in the docker compose file. But since I am accessing it over tailscale, I wanted to share my solution. I set the following in my compose.yml file:

```
      INVIDIOUS_CONFIG: |
        # ...
        external_port: <tailscale serve port>
        domain: <hostname>.<magic-dns>.ts.net
        https_only: true
        statistics_enabled: false
        hmac_key: "<hmac_key>"

```

The problem persisted with `docker compose restart invidious`, and instead I had to run

```
docker compose down invidious
docker compose up -d invidious
```

to get it to work.
