### ISSUE TITLE
Audio only mode

### ISSUE THREAD

**Issue by 8mpty** [lamarios/clipious#52]
*Disclaimer*
*These are just some suggestions and I am unsure it is even possible to implement these features or if it breaks stuff and TOS for some reason but its still all up to the developer.*
*I AM NOT FORCING ANYONE TO IMPLEMENT THESE FEATURES JUST A HEADS UP*

[Features]
1. add the option to choose between viewing the video as it is or just the audio. may also add a different interfaces when  the "audio only" option is selected to something like YT Music (just a reference).

2. add a download button to download the videos or audio like in the default invidious websites and save them to a folder that is either predefined like the android downloads/videos/audio folder or let the user choose/make the directory themselves. 

The app can then maybe have a separate "tab" or slide-in menu that lists out the downloaded videos/audio and is able to view it in the app in a separate activity tab for only the downloaded files. or when the user searches for the same video or audio, the app can then just use the "download/cached" files instead and not waste bandwidth or data just like iTube/BG Player. reference (https://www.youtube.com/watch?v=qc-EwBtSdBU) not my video btw but i do have the app XD.

3. find a way to detect the if its a landscape video and will then set it to landscape since on my side, all videos are still in portrait mode and i would have to enable auto-rotate (i normally don't enable it). 

4. could also add timers, that is set up by the user, to turn the video or audio off automatically once the timer ends.

**Comment by lamarios** [comment]
This will be video download in the next release with a couple of caveats:

- No quality options for now, invidious only offers 340p and 720p for both video and audio, i don't think 340p is acceptable so it will download 720p.
- no audio only because the app doesn't handle audio only playback


1. Audio only is on the roadmap.
3. there should be an option for that already
4. won't do

I'll modify the title of the issue to focus on audio only mode as the rest is considered done
