### ISSUE TITLE
Allow login using the Cookie SID

### ISSUE THREAD

**Issue by ranton1990** [lamarios/clipious#54]
App Version: 1.2.0
Build: 1123

**Subscriptions + Playlists**
Observed Behavior: "Videos konnten nicht abgerufen werden. Tippen Sie, um es erneut zu versuchen." de->en: “Videos could not be loaded. Tap to try again”

**Channels**
Observed Behavior: Tapping on a channel name gives me an infinite loading screen.

**Comments**
Observed Behavior: "FormatException: Unexpected character (at character 1)<html>^

**Comment by lamarios** [comment]
Are you using your own server? If yes. Do you mind sharing the url? If no please share the url.

**Comment by ranton1990** [comment]
Yes I am, and I'm actually using basic auth on it to prevent access, because it's a private instance. Could I send you the URL privately? Or if that helps, it's in this style: https://username:password@subdomain.domain.de.
Playback works flawless like this.

**Comment by lamarios** [comment]
Hmm interesting. That might be the issue. If you don't mind you can send me at my github username at Gmail. Com

**Comment by ranton1990** [comment]
Sent you the link via mail.

**Comment by lamarios** [comment]
Thanks. I'll have a look.

**Comment by lamarios** [comment]
Ok, yeah I don't think i can fix it unfortunately.  When using  https://xxx:xxx@xxx.com it actually creates an Authorization header that is overwritten by the one needed by the application to connect to authenticated endpoints.
Channel breaks because as you're logged in to the server it requires to know the channel subscriptions status, if i delete the server and re-add it without logging in, channel page works. 

For the comments it's a bug, it's sending the authentication header but it's actually not necessary. I'll fix this.

**Comment by ranton1990** [comment]
What if I used the same user and password account and basic auth?

**Comment by lamarios** [comment]
that won't work, different type of authentication. 
The  https://xxx:yyy@zzz.com is using Authorization: Basic while for authenticated invidious endpoints i'm using Authorization: Bearer 

But thinking about it, there's a way i could fix it, invidious allows two ways to authenticate with a server. I could try the second one that rely on cookies rather than tokens. That should work.

**Comment by ranton1990** [comment]
I have seen multiple instances using basic auth, so this could apply to several people.

**Comment by lamarios** [comment]
Alright, I'll make this one on my priority so more people can use the app

**Comment by ranton1990** [comment]
Pls report back, if you don't need the account on my instance anymore.

**Comment by lamarios** [comment]
Maybe keep it until i close this if you don't mind so I can test properly

**Comment by ranton1990** [comment]
Will do.

**Comment by lamarios** [comment]
fix is in version 1.3.0
