### ISSUE TITLE
Unbelievably overbloated APK files since update “1.21.0”

### ISSUE THREAD

**Issue by NAKADZI** [lamarios/clipious#605]
**Describe the іssue**
Starting with the [1.21.0](https://github.com/lamarios/clipious/releases/tag/1.21.0) update, all types _(ARMv7, x86, etc.)_ of APK files received an incredibly disproportionate increase in size (almost 3 times more) relative to the new minor features obtained.

**Expected behavior**
Corresponding optimization of the size of the final APK files, which was perfectly implemented up to version [1.20.0](https://github.com/lamarios/clipious/releases/tag/1.20.0).
This is very useful for budget devices with only **16** or **8** GB of internal memory.

**Screenshots**
![Screen-808](https://github.com/user-attachments/assets/bdb69f17-4792-4aa1-b8f6-e07b983c2e19)

**Additional context**
I have a personal example of a budget device with **8 GB** of internal memory (which is almost fully filled with a minimal set of necessary apps), which is my main mobile device.

**Comment by lamarios** [comment]
People ask for feature. I implement them. 

I've been asked multiple time for better quality downloads. To do so I need to dwonalod the audio and the video separately then merge them together. This is done with FFMPEG. Which is why the APK size increased. 

I currently don't have much bandwidth to allocate to the app development, I have even less to implement and maintain different flavours of the app. 

If you have a better solution for the audio / video problem. Please contribute and submit a PR.
