### ISSUE TITLE
"Video player" hogs the screen in landscape

### ISSUE THREAD

**Issue by D4RKW1NT3R** [lamarios/clipious#99]
The video player title hogs up the screen in landscape mode and makes it so the bottom half of the screen doesn't show.
![Screenshot_20230407-002159](https://user-images.githubusercontent.com/57409539/230546558-d85f2844-94e3-4f8e-a8dc-59696e4303b4.png)

**Comment by lamarios** [comment]
I'm not sure i'll look into this. It is very hard to build a good landscape ui for a video player. Unless someone contributes.

**Comment by ganeshlab** [comment]
What about something like auto fullscreen while a video is playing in landscape mode?

**Comment by lamarios** [comment]
Sure, unfortunately it's probably the most messy part of the project because  I wanted to keep the player from reloading the video when switching from the small bottom of the screen player to the full page one.

The actual video player is here:
https://github.com/lamarios/clipious/blob/master/lib/views/miniPlayer.dart#L29

the controls for when it's the big player showing:
https://github.com/lamarios/clipious/blob/master/lib/views/videoPlayer/fullScreenView.dart

@ganeshlab that's actually a good suggestion.

**Comment by c00lhawk607** [comment]
> What about something like auto fullscreen while a video is playing in landscape mode? 

That's pretty much what I meant but couldn't put to words lol

**Comment by lamarios** [comment]
in that case, the code would most likely be in the this file:

https://github.com/lamarios/clipious/blob/master/lib/controllers/miniPayerController.dart

**Comment by lamarios** [comment]
the app now switches to full screen by default on landscape. closing this
